name: Release libfuzzer-dotnet

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - 'libfuzzer-dotnet-windows.cc'
      - 'libfuzzer-dotnet.cc'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: windows-latest
    needs: build

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: libfuzzer-dotnet-*
          merge-multiple: true
      - name: Tag
        id: tag
        run: |
          $tag = "v" + (Get-Date).ToString("yyyy.MM.dd.HHmm")
          Add-Content -Path $env:GITHUB_OUTPUT -Value "tag=$tag"

          git config user.name "${{ github.repository_owner }}"
          git config user.email "${{ github.repository_owner }}@users.noreply.github.com"

          git tag -a $tag -m $tag ${{ github.sha }}
          git push origin $tag
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            libfuzzer-dotnet-windows.exe
            libfuzzer-dotnet-ubuntu
            libfuzzer-dotnet-debian
          tag_name: ${{ steps.tag.outputs.tag }}
